[package]
name = "cm7"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
stm32h7-staging = { version = "0.17.0", default-features = false, features = [
  "stm32h747cm7",
] }
shared = { path = "../shared" }
cortex-m = "0.7.7"
postcard = { version = "1", default-features = false }

[build-dependencies]
object = "0.39.1"
